name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Normal build
        run: cargo build
      - name: Build all targets
        run: cargo build --all-targets
      - name: Build everything
        run: cargo build --all-targets --all-features
      - name: Run tests
        run: cargo test --all-features
